INSERT INTO TBL_SELLER (NAME, SALARY, BONUS, GENDER) 
VALUES ('Afonso', 10000, 15, 1);

INSERT INTO TBL_SELLER (NAME, SALARY, BONUS, GENDER) 
VALUES ('Fernanda', 15000.99, 13.5, 0);

INSERT INTO TBL_SELLER (NAME, SALARY, BONUS, GENDER) 
VALUES ('Clovis', 1500, 5, 1);